[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
capnpc = "0.18"

[dependencies]
capnp  = "0.18"

[lib]
name = "rust_core"
crate-type = ["staticlib"]
